#!/bin/bash -ex

VER="2.1.7"
URL=https://github.com/magento/magento2

ADMIN_NAME=admin
ADMIN_PASS=turnkey1 # requires at least 1 number, argh!
ADMIN_MAIL=admin@example.com
DOMAIN=127.0.0.1

DB_NAME=magento
DB_USER=magento
DB_PASS=$(mcookie)

WEBROOT=/var/www/magento

git clone --depth 1 --branch $VER $URL $WEBROOT

mv /usr/local/src/TurnKey $WEBROOT/app/code/

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql server
/etc/init.d/mysql start

# create database
$MYSQL_ADMIN create $DB_NAME

# create database user with privileges on the database
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS';"

# update apache configuration
a2dissite 000-default
a2ensite magento
a2enmod rewrite

# increase memory limit to upstream recommendation
sed -i 's|^memory_limit.*|memory_limit = 756M|' /etc/php5/cli/php.ini

cd $WEBROOT
composer install
cd -

# configure magento
php -f $WEBROOT/bin/magento -- setup:install \
    --language en_US \
    --timezone "Europe/London" \
    --currency USD \
    --db-host localhost \
    --db-name $DB_NAME \
    --db-user $DB_USER \
    --db-password $DB_PASS \
    --base-url "http://$DOMAIN/" \
    --base-url-secure "https://$DOMAIN/" \
    --use-rewrites 1 \
    --use-secure 1 \
    --use-secure-admin 1 \
    --admin-firstname Store \
    --admin-lastname Admin \
    --admin-user $ADMIN_NAME \
    --admin-password $ADMIN_PASS \
    --admin-email "$ADMIN_MAIL" \
    --key $(mcookie)

php -f $WEBROOT/bin/magento -- setup:static-content:deploy
php -f $WEBROOT/bin/magento -- cache:flush
php -f $WEBROOT/bin/magento -- indexer:reindex
php -f $WEBROOT/bin/magento -- setup:di:compile

ADMIN_URI=$( php -f $WEBROOT/bin/magento -- info:adminuri | grep -o '/.*$' )

# create getting-started page
$MYSQL_BATCH --execute "use $DB_NAME; update cms_page SET content = '<div class=\"page-title\"> <h2>Welcome to TurnKey Magento</h2> </div> <h3>Let\'s get you started:&nbsp;</h3> <p><span style=\"font-weight: normal; font-size: 12px;\"><br />-&nbsp;Log into the <a href=\"$ADMIN_URI\">administration panel</a> as <strong>$ADMIN_NAME</strong> and get going\!</span></p> <p><span style=\"font-weight: normal; font-size: 12px;\">-&nbsp;</span><a href=\"https://www.turnkeylinux.org/magento\">TurnKey Linux Magento appliance release notes</a></p> <p>-&nbsp;<a href=\"http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/welcome_to_the_magento_user_s_guide\">Magento user guide (everything you need to know to get started)</a></p> <p>-&nbsp;<a href=\"http://www.magentocommerce.com/knowledge-base\">Magento knowledge base (articles, tutorials, screencasts, documentation)</a></p>' where cms_page.page_id=2;"

chmod -R 755 $WEBROOT
chown -R www-data:www-data $WEBROOT

# Mark all default messages as read
#  as this will hide patch notifications, when building new version check for new patches before release
$MYSQL_BATCH --execute "USE $DB_NAME; UPDATE adminnotification_inbox SET is_read=1;"

# stop mysql
/etc/init.d/mysql stop


