#!/usr/bin/env bash

WEBROOT=/var/www/magento

# Function to install patch
function install_patch {
    cd $WEBROOT
    mv /tmp/patches/${1} .
    chmod +x ${1}
    ./${1}
    rm ./${1}
}

#install_patch "PATCH_SUPEE-6285_CE_1.9.1.1_v2-2015-07-08-08-07-43.sh"

echo "yes" | apt-get purge patch
