#!/usr/bin/env bash

# Function to install patch


function install_patch {
    cd /var/www/magento
    mv /tmp/patches/${1} .
    chmod +x ${1}
    ./${1}
    rm ./${1}
}

install_patch "PATCH_SUPEE-4829_EE_1.14.1.0_v1-2015-02-10-07-57-21.sh"  
install_patch "PATCH_SUPEE-5344_CE_1.8.0.0_v1-2015-02-10-08-10-38.sh"

echo "yes" | apt-get purge patch
