#!/bin/bash -e
# regenerate magento secrets

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/magento/app/etc/env.php
    sed -i "s|'${1}' => '.*'|'${1}' => '${2}'|" ${CONF}
}

PASSWORD=$(mcookie)
ENCRYPTION_KEY=$(mcookie)

updateconf password $PASSWORD
updateconf key $ENCRYPTION_KEY

$INITHOOKS_PATH/bin/mysqlconf.py --user=magento --pass="$PASSWORD"
