#!/bin/bash -e
# regenerate magento secrets

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/magento/app/etc/local.xml
    sed -i "s|<$1><!\[CDATA\(.*\)]]></$1>|<$1><!\[CDATA\[$2]]></$1>|" $CONF
}

PASSWORD=$(mcookie)
ENCRYPTION_KEY=$(mcookie)

updateconf password $PASSWORD
updateconf key $ENCRYPTION_KEY

$INITHOOKS_PATH/bin/mysqlconf.py --user=magento --pass="$PASSWORD"
